import './globals.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from './component/layout/Header'
import Footer from './component/views/Footer'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mishal E-Commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className='px-8'>
            <Header />
            {children}
          </main>
          <Footer />
        </body>
      </html>
      </ClerkProvider>
  )
}
